const EXAMPLE_SUBMIT = {
  numero_or: 999,
  matricula: "asdasd",
  kms: "asdasdsa",
  data_proxima_itv: "2024-12-05T16:49:40.519Z",
  fim_de_garantia: "2024-12-05T16:49:40.519Z",
  contrato_manutencao: "dasdasdasdas",
  nivel_combustivel: "option-two",
  dots: {
    mossa: [
      {
        id: 1,
        x: 34,
        y: 212,
        value: "1",
        status: false,
      },
      {
        id: 2,
        x: 71,
        y: 217,
        value: "2",
        status: false,
      },
      {
        id: 3,
        x: 52,
        y: 284,
        value: "3",
        status: false,
      },
      {
        id: 4,
        x: 52,
        y: 347,
        value: "4",
        status: false,
      },
      {
        id: 5,
        x: 34,
        y: 401,
        value: "5",
        status: false,
      },
      {
        id: 6,
        x: 82,
        y: 407,
        value: "6",
        status: false,
      },
      {
        id: 7,
        x: 197,
        y: 540,
        value: "7",
        status: false,
      },
      {
        id: 8,
        x: 312,
        y: 397,
        value: "8",
        status: false,
      },
      {
        id: 9,
        x: 355,
        y: 391,
        value: "9",
        status: false,
      },
      {
        id: 10,
        x: 327,
        y: 332,
        value: "10",
        status: false,
      },
      {
        id: 11,
        x: 333,
        y: 267,
        value: "11",
        status: false,
      },
      {
        id: 12,
        x: 313,
        y: 206,
        value: "12",
        status: false,
      },
      {
        id: 13,
        x: 355,
        y: 202,
        value: "13",
        status: false,
      },
      {
        id: 14,
        x: 194,
        y: 47,
        value: "14",
        status: false,
      },
      {
        id: 15,
        x: 194,
        y: 180,
        value: "15",
        status: false,
      },
      {
        id: 16,
        x: 194,
        y: 243,
        value: "16",
        status: false,
      },
      {
        id: 17,
        x: 143,
        y: 280,
        value: "17",
        status: false,
      },
      {
        id: 18,
        x: 248,
        y: 280,
        value: "18",
        status: false,
      },
      {
        id: 19,
        x: 144,
        y: 334,
        value: "19",
        status: false,
      },
      {
        id: 21,
        x: 246,
        y: 334,
        value: "21",
        status: false,
      },
      {
        id: 22,
        x: 197,
        y: 404,
        value: "22",
        status: false,
      },
      {
        id: 23,
        x: 197,
        y: 442,
        value: "23",
        status: false,
      },
    ],
    risco: [
      {
        id: 1,
        x: 34,
        y: 212,
        value: "1",
        status: false,
      },
      {
        id: 2,
        x: 71,
        y: 217,
        value: "2",
        status: false,
      },
      {
        id: 3,
        x: 52,
        y: 284,
        value: "3",
        status: false,
      },
      {
        id: 4,
        x: 52,
        y: 347,
        value: "4",
        status: false,
      },
      {
        id: 5,
        x: 34,
        y: 401,
        value: "5",
        status: false,
      },
      {
        id: 6,
        x: 82,
        y: 407,
        value: "6",
        status: false,
      },
      {
        id: 7,
        x: 197,
        y: 540,
        value: "7",
        status: false,
      },
      {
        id: 8,
        x: 312,
        y: 397,
        value: "8",
        status: false,
      },
      {
        id: 9,
        x: 355,
        y: 391,
        value: "9",
        status: false,
      },
      {
        id: 10,
        x: 327,
        y: 332,
        value: "10",
        status: false,
      },
      {
        id: 11,
        x: 333,
        y: 267,
        value: "11",
        status: false,
      },
      {
        id: 12,
        x: 313,
        y: 206,
        value: "12",
        status: false,
      },
      {
        id: 13,
        x: 355,
        y: 202,
        value: "13",
        status: false,
      },
      {
        id: 14,
        x: 194,
        y: 47,
        value: "14",
        status: false,
      },
      {
        id: 15,
        x: 194,
        y: 180,
        value: "15",
        status: false,
      },
      {
        id: 16,
        x: 194,
        y: 243,
        value: "16",
        status: false,
      },
      {
        id: 17,
        x: 143,
        y: 280,
        value: "17",
        status: false,
      },
      {
        id: 18,
        x: 248,
        y: 280,
        value: "18",
        status: false,
      },
      {
        id: 19,
        x: 144,
        y: 334,
        value: "19",
        status: false,
      },
      {
        id: 21,
        x: 246,
        y: 334,
        value: "21",
        status: false,
      },
      {
        id: 22,
        x: 197,
        y: 404,
        value: "22",
        status: false,
      },
      {
        id: 23,
        x: 197,
        y: 442,
        value: "23",
        status: false,
      },
    ],
    outros_danos: [
      {
        id: 1,
        x: 34,
        y: 212,
        value: "1",
        status: false,
      },
      {
        id: 2,
        x: 71,
        y: 217,
        value: "2",
        status: false,
      },
      {
        id: 3,
        x: 52,
        y: 284,
        value: "3",
        status: false,
      },
      {
        id: 4,
        x: 52,
        y: 347,
        value: "4",
        status: false,
      },
      {
        id: 5,
        x: 34,
        y: 401,
        value: "5",
        status: false,
      },
      {
        id: 6,
        x: 82,
        y: 407,
        value: "6",
        status: false,
      },
      {
        id: 7,
        x: 197,
        y: 540,
        value: "7",
        status: false,
      },
      {
        id: 8,
        x: 312,
        y: 397,
        value: "8",
        status: false,
      },
      {
        id: 9,
        x: 355,
        y: 391,
        value: "9",
        status: false,
      },
      {
        id: 10,
        x: 327,
        y: 332,
        value: "10",
        status: false,
      },
      {
        id: 11,
        x: 333,
        y: 267,
        value: "11",
        status: false,
      },
      {
        id: 12,
        x: 313,
        y: 206,
        value: "12",
        status: false,
      },
      {
        id: 13,
        x: 355,
        y: 202,
        value: "13",
        status: false,
      },
      {
        id: 14,
        x: 194,
        y: 47,
        value: "14",
        status: false,
      },
      {
        id: 15,
        x: 194,
        y: 180,
        value: "15",
        status: false,
      },
      {
        id: 16,
        x: 194,
        y: 243,
        value: "16",
        status: false,
      },
      {
        id: 17,
        x: 143,
        y: 280,
        value: "17",
        status: false,
      },
      {
        id: 18,
        x: 248,
        y: 280,
        value: "18",
        status: false,
      },
      {
        id: 19,
        x: 144,
        y: 334,
        value: "19",
        status: false,
      },
      {
        id: 21,
        x: 246,
        y: 334,
        value: "21",
        status: false,
      },
      {
        id: 22,
        x: 197,
        y: 404,
        value: "22",
        status: false,
      },
      {
        id: 23,
        x: 197,
        y: 442,
        value: "23",
        status: false,
      },
    ],
    estalado: [
      {
        id: 1,
        x: 195,
        y: 242,
        value: "Parabrisa",
        status: false,
      },
      {
        id: 2,
        x: 143,
        y: 279,
        value: "Vidro Lateral Frente Esquerdo",
        status: false,
      },
      {
        id: 3,
        x: 247,
        y: 280,
        value: "Vidro Lateral Frente Direito",
        status: false,
      },
      {
        id: 4,
        x: 143,
        y: 333,
        value: "Vidro Lateral Trás Esquerdo",
        status: false,
      },
      {
        id: 5,
        x: 247,
        y: 335,
        value: "Vidro Lateral Trás Direito",
        status: false,
      },
      {
        id: 6,
        x: 195,
        y: 404,
        value: "Óculo",
        status: false,
      },
    ],
    picado: [
      {
        id: 1,
        x: 195,
        y: 242,
        value: "Parabrisa",
        status: false,
      },
      {
        id: 2,
        x: 143,
        y: 279,
        value: "Vidro Lateral Frente Esquerdo",
        status: false,
      },
      {
        id: 3,
        x: 247,
        y: 280,
        value: "Vidro Lateral Frente Direito",
        status: false,
      },
      {
        id: 4,
        x: 143,
        y: 333,
        value: "Vidro Lateral Trás Esquerdo",
        status: false,
      },
      {
        id: 5,
        x: 247,
        y: 335,
        value: "Vidro Lateral Trás Direito",
        status: false,
      },
      {
        id: 6,
        x: 195,
        y: 404,
        value: "Óculo",
        status: false,
      },
    ],
    partido: [
      {
        id: 1,
        x: 195,
        y: 242,
        value: "Parabrisa",
        status: false,
      },
      {
        id: 2,
        x: 143,
        y: 279,
        value: "Vidro Lateral Frente Esquerdo",
        status: false,
      },
      {
        id: 3,
        x: 247,
        y: 280,
        value: "Vidro Lateral Frente Direito",
        status: false,
      },
      {
        id: 4,
        x: 143,
        y: 333,
        value: "Vidro Lateral Trás Esquerdo",
        status: false,
      },
      {
        id: 5,
        x: 247,
        y: 335,
        value: "Vidro Lateral Trás Direito",
        status: false,
      },
      {
        id: 6,
        x: 195,
        y: 404,
        value: "Óculo",
        status: false,
      },
    ],
  },
  iluminacao_frente: ["Luz Diurna Drt"],
  iluminacao_tras: ["Luz Presenças Esq"],
  tapetes: ["Tapete Mala"],
  climatizacao: ["Desinfeção por Ozono"],
  escovas_limpa_vidros: ["Escovas Frt"],
  chapas_matricula: "Sem Danos",
  pneus_alinhamento_direcao: ["Pneus Frente"],
  lavagem: ["Vue"],
  passaporte_servico: "OK",
  injecao: ["Limpeza Sistema Injeção"],
  anti_roubo_rodas: "OK",
  colete_triangulo: ["Colete em falta"],
  pneu_suplente: "OK",
  antena: "OK",
  observacoes: "OBS",
  imagens: [
    {
      path: "./Captura de ecrã 2024-12-04, às 14.36.39.png",
      relativePath: "./Captura de ecrã 2024-12-04, às 14.36.39.png",
      preview:
        "blob:http://localhost:3000/bc7e3315-44cb-49b4-b366-bac0797700cf",
    },
    {
      path: "./Captura de ecrã 2024-12-04, às 14.36.24.png",
      relativePath: "./Captura de ecrã 2024-12-04, às 14.36.24.png",
      preview:
        "blob:http://localhost:3000/77526f0c-65bb-4e6e-bd1f-e749e0190290",
    },
    {
      path: "./Captura de ecrã 2024-12-04, às 09.16.54.png",
      relativePath: "./Captura de ecrã 2024-12-04, às 09.16.54.png",
      preview:
        "blob:http://localhost:3000/653cc885-bbce-4509-8e4b-2bf713deecf4",
    },
  ],
};

const TOKENS = {
  access_token:
    "1000.382733d38683aac8324997354bb0d51d.c419daa5f44cb15d6bcfc6843308696e",
  refresh_token:
    "1000.7ab9754631333f161d540005b5d21232.844b49d780ae787092554c1d0ca8df77",
  scope:
    "ZohoCRM.users.ALL ZohoCRM.org.ALL ZohoCRM.settings.ALL ZohoCRM.modules.ALL ZohoCRM.bulk.ALL ZohoCRM.coql.READ",
  api_domain: "https://www.zohoapis.com",
  token_type: "Bearer",
  expires_in: 3600,
};
